apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nosql.fullname" . }}
  labels:
    {{- include "nosql.labels" . | nindent 4 }}
data:
  mongo-init.js: |
    db = db.getSiblingDB('admin');
    db.auth(
        process.env.MONGO_INITDB_ROOT_USERNAME,
        process.env.MONGO_INITDB_ROOT_PASSWORD,
    );
    db = db.getSiblingDB(process.env.MONGO_INITDB_DATABASE);
    db.createUser(
      {
        user: process.env.MONGO_INITDB_USERNAME,
        pwd: process.env.MONGO_INITDB_PASSWORD,
        roles: [
          {
            role: "readWrite",
            db: process.env.MONGO_INITDB_DATABASE,
          }
        ]
      }
    );
