apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "nosql.fullname" . }}
  labels:
    {{- include "nosql.labels" . | nindent 4 }}
spec:
  storageClassName: hostpath
  accessModes:
  {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  capacity:
    storage: {{ .Values.persistence.size }}
  hostPath:
    path: {{ .Values.persistence.hostPath }}/{{ include "nosql.fullname" . }}
