apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nosql.fullname" . }}
  labels:
    {{- include "nosql.labels" . | nindent 4 }}
spec:
  storageClassName: hostpath
  volumeName: {{ include "nosql.fullname" . }}
  accessModes:
  {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
