apiVersion: v1
kind: Service
metadata:
  name: {{ include "nosql.fullname" . }}
  labels:
    {{- include "nosql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: nosql
      protocol: TCP
      name: nosql
  selector:
    {{- include "nosql.selectorLabels" . | nindent 4 }}
